-- First, remove the table if it exists
drop table if exists bookmarks;

-- Create the table anew
create table bookmarks (
  id INTEGER primary key generated by default as identity,
  title text,
  url VARCHAR,
  rating integer,
  description text

);

-- insert some test data
-- Using a multi-row insert statement here
insert into bookmarks (title, url)
values
  ('A site', 'www.site.com'),
  ('Another site', 'www.address.com'),
  ('Final site', 'www.final.com');